vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        image_file:
            uri_prefix: '%image_dir%'
            upload_destination: '%kernel.project_dir%/public/%image_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer 